export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

export const GAME_STATUS = {
  ONGOING: 'ONGOING',
  FINISHED: 'FINISHED'
};

export const RESERVATION_STATUS = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

export const TEAM_COLORS = {
  RED: 'RED',
  BLUE: 'BLUE'
};

export const PLAYER_ROLES = {
  ATTACK: 'ATTACK',
  DEFENSE: 'DEFENSE'
};

export const TABLE_CONDITIONS = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  WORN: 'WORN',
  NEEDS_MAINTENANCE: 'NEEDS_MAINTENANCE'
};

